//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarStoreWeb.CarStoreService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CarStoreService.IProductService")]
    public interface IProductService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductService/Create", ReplyAction="http://tempuri.org/IProductService/CreateResponse")]
        void Create(CarStoreViewModels.ProductViewModel item);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductService/Create", ReplyAction="http://tempuri.org/IProductService/CreateResponse")]
        System.Threading.Tasks.Task CreateAsync(CarStoreViewModels.ProductViewModel item);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductService/Read", ReplyAction="http://tempuri.org/IProductService/ReadResponse")]
        CarStoreViewModels.ProductViewModel[] Read();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductService/Read", ReplyAction="http://tempuri.org/IProductService/ReadResponse")]
        System.Threading.Tasks.Task<CarStoreViewModels.ProductViewModel[]> ReadAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductService/Update", ReplyAction="http://tempuri.org/IProductService/UpdateResponse")]
        void Update(CarStoreViewModels.ProductViewModel item);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductService/Update", ReplyAction="http://tempuri.org/IProductService/UpdateResponse")]
        System.Threading.Tasks.Task UpdateAsync(CarStoreViewModels.ProductViewModel item);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductService/Destroy", ReplyAction="http://tempuri.org/IProductService/DestroyResponse")]
        void Destroy(CarStoreViewModels.ProductViewModel item);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductService/Destroy", ReplyAction="http://tempuri.org/IProductService/DestroyResponse")]
        System.Threading.Tasks.Task DestroyAsync(CarStoreViewModels.ProductViewModel item);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductService/GetCategories", ReplyAction="http://tempuri.org/IProductService/GetCategoriesResponse")]
        CarStoreViewModels.ProductCategoryViewModel[] GetCategories();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductService/GetCategories", ReplyAction="http://tempuri.org/IProductService/GetCategoriesResponse")]
        System.Threading.Tasks.Task<CarStoreViewModels.ProductCategoryViewModel[]> GetCategoriesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductService/GetMaterials", ReplyAction="http://tempuri.org/IProductService/GetMaterialsResponse")]
        CarStoreViewModels.ProductMaterialViewModel[] GetMaterials();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductService/GetMaterials", ReplyAction="http://tempuri.org/IProductService/GetMaterialsResponse")]
        System.Threading.Tasks.Task<CarStoreViewModels.ProductMaterialViewModel[]> GetMaterialsAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IProductServiceChannel : CarStoreWeb.CarStoreService.IProductService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ProductServiceClient : System.ServiceModel.ClientBase<CarStoreWeb.CarStoreService.IProductService>, CarStoreWeb.CarStoreService.IProductService {
        
        public ProductServiceClient() {
        }
        
        public ProductServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ProductServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProductServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProductServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void Create(CarStoreViewModels.ProductViewModel item) {
            base.Channel.Create(item);
        }
        
        public System.Threading.Tasks.Task CreateAsync(CarStoreViewModels.ProductViewModel item) {
            return base.Channel.CreateAsync(item);
        }
        
        public CarStoreViewModels.ProductViewModel[] Read() {
            return base.Channel.Read();
        }
        
        public System.Threading.Tasks.Task<CarStoreViewModels.ProductViewModel[]> ReadAsync() {
            return base.Channel.ReadAsync();
        }
        
        public void Update(CarStoreViewModels.ProductViewModel item) {
            base.Channel.Update(item);
        }
        
        public System.Threading.Tasks.Task UpdateAsync(CarStoreViewModels.ProductViewModel item) {
            return base.Channel.UpdateAsync(item);
        }
        
        public void Destroy(CarStoreViewModels.ProductViewModel item) {
            base.Channel.Destroy(item);
        }
        
        public System.Threading.Tasks.Task DestroyAsync(CarStoreViewModels.ProductViewModel item) {
            return base.Channel.DestroyAsync(item);
        }
        
        public CarStoreViewModels.ProductCategoryViewModel[] GetCategories() {
            return base.Channel.GetCategories();
        }
        
        public System.Threading.Tasks.Task<CarStoreViewModels.ProductCategoryViewModel[]> GetCategoriesAsync() {
            return base.Channel.GetCategoriesAsync();
        }
        
        public CarStoreViewModels.ProductMaterialViewModel[] GetMaterials() {
            return base.Channel.GetMaterials();
        }
        
        public System.Threading.Tasks.Task<CarStoreViewModels.ProductMaterialViewModel[]> GetMaterialsAsync() {
            return base.Channel.GetMaterialsAsync();
        }
    }
}
