//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarStoreService
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductMaterial
    {
        public ProductMaterial()
        {
            this.Products = new HashSet<Product>();
        }
    
        public int MaterialID { get; set; }
        public string MaterialName { get; set; }
    
        public virtual ICollection<Product> Products { get; set; }
    }
}
